### ISSUE TITLE
EPIC - Introduce new API Specs and infra creation flow

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes-sigs/cluster-api-provider-ibmcloud#1611]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
This epic covers all the task items involved as part of the process to complete the entire PowerVS infra creation via CAPIBM.

**Completed**
* [x]  #1485
* [x]  #1488
* [x]  #1592
* [x]  #1605
* [x]  #1599
* [x]  #1600

**TO-DO**
* [x]  #1451
* [x]  #1607 
* [x]  #1647 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Karthik-K-N** [comment]
Some of the review comments which needs to be addressed

- [ ] Have proper resource state handling and avoid returning error
- [ ] Revisit logs messages
- [ ] reconcileNetwork - reconcile DHCP server and network separately
- [ ] Check about how to test in staging environment as machine types are different
- [ ] Fix gocyclo measure and avoid //nollint
- [ ] Reconcile VPC - separate the security group from it and handle it outside
- [ ] Check on how to use and handle exisitng TG and connections
- [ ] Revisit when the IBMPowerVSMachine should be set as ready after updating Machine IP in LB and all operations are done or before
- [ ] Rewrite LB pool memeber addition -- revisit the logic, it looks complicated
- [ ] Optmise checking and setting status for resources
- [ ] Have defined types for recurring errors
- [ ] Validate a case when invalid ID is passed while getting a resource — check how API behaves
- [ ] optimise LB pool member creation
- [ ] Add a check before importing or using IBMPowerVSImage and execute only if IBMPowerVSCluster is ready
- [ ] How to handle if machine has multiple internal IPs
- [ ] Revisit adding/setting/updating listeners in LB creation

**Comment by Karthik-K-N** [comment]
> Some of the review comments which needs to be addressed
> 
>     * [x]  Have proper resource state handling and avoid returning error
>       PR: [Avoid returning error when resource creation and deletion is in progress #1693](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1693)* [x]  Revisit logs messages
>         
>         * [Refactor logging #1755](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1755)[ ]  reconcileNetwork - reconcile DHCP server and network separately[ ]  Check about how to test in staging environment as machine types are different[ ]  Fix gocyclo measure and avoid //nollint* [x]  Reconcile VPC - separate the security group from it and handle it outside
>         
>         * [Support VPC security group for PowerVS clusters #1738](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1738)* [x]  Check on how to use and handle exisitng TG and connections
>         
>         * [Attach connections to existing transit gateway when its not there #1901](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1901)* [Refactor transit gateway status #1961](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1961)[ ]  Revisit when the IBMPowerVSMachine should be set as ready after updating Machine IP in LB and all operations are done or before[ ]  Rewrite LB pool memeber addition -- revisit the logic, it looks complicated* [x]  Optmise checking and setting status for resources
>         
>         * [Refactor reconcilation of resources #1937](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1937)[ ]  Have defined types for recurring errors
>       - [Improve IBMPowerVSCluster deletion #1825](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1825)[x]  Validate a case when invalid ID is passed while getting a resource — check how API behaves
>       - [Refactor reconcilation of resources #1937](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1937)[ ]  optimise LB pool member creation[ ]  Add a check before importing or using IBMPowerVSImage and execute only if IBMPowerVSCluster is ready[ ]  How to handle if machine has multiple internal IPs[ ]  Revisit adding/setting/updating listeners in LB creation

Uncompleted items in this list will be completed as part of https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2129
hence closing this issue
/close
