### ISSUE TITLE
EPIC: Add UT accross various files in repository

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1818]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Recently we added lots of functionality but haven't added any corresponding UT's to it. Its time to add unit test cases and overall goal is to reach 80% of test coverage.

As a non-goal during the time of adding UT if we find any redundant or unwanted or code duplication, a separate PR needs to be submitted to optimize the code.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- [ ] cloud/scope/powervs_cluster.go 
- [ ] cloud/scope/powervs_machine.go 

Instructions for running individual tests on VS Code

1. Get kubebuilder asset path
```
$ cd cluster-api-provider-ibmcloud
$ make setup-envtest
kube-builder assets set using darwin OS at location /Users/karthikkn/Library/Application Support/io.kubebuilder.envtest/k8s/1.29.3-darwin-amd64
```

2. Create settings.json file with kubebuilder asset path
```
$ cd cluster-api-provider-ibmcloud/.vscode
$ cat settings.json
cat settings.json
{
    "go.testEnvVars": {
        "KUBEBUILDER_ASSETS": "/Users/karthikkn/Library/Application Support/io.kubebuilder.envtest/k8s/1.29.3-darwin-amd64",
    },
}

```
3. Run individual test by clicking on run test above test function name in VS Code editor

Instructions for checking code coverage of file 

1. Generate the test coverage html page
```
$ cd cluster-api-provider-ibmcloud/.vscode
$ make test-cover
```
A file named cover.html will be created under cluster-api-provider-ibmcloud directory

example path: /Users/karthikkn/k8-workspace/cluster-api-provider-ibmcloud/cover.html

2. Copy the path of the file and paste in browser to view the html page and select the file to view the lines covered in UT.

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/2fd2c8e4-52eb-429a-acae-c09ab8b24592">

```[tasklist]
### Helper PRs
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1913
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1899
```

```[tasklist]
### UT PRs
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1912
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1927
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1928
```

**Comment by Amulyam24** [comment]
Will take up adding UT for `cloud/scope/powervs_cluster.go`

**Comment by Karthik-K-N** [comment]
We will add UT for ibmpowervscluster_controller.go file once we finalize and fix the issue https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1837 as it  involves some code refactoring.

**Comment by Karthik-K-N** [comment]
If contributing to this issue, Please do comment here with function name to avoid multiple folks working on same thing.

**Comment by Shilpa-Gokul** [comment]
I am working on adding UT for ReconcileNetwork, ReconcileVPC and ReconcileVPCSubnets function

**Comment by carmal891** [comment]
Picking up UT for the ReconcileLoadBalancers function

**Comment by arshadd-b** [comment]
Picking up UT for ReconcileVPCSecurityGroups function

**Comment by arshadd-b** [comment]
Picking up UT for ReconcileTransitGateway function

**Comment by Karthik-K-N** [comment]
Unfortunately we discovered this bug https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2026, which could have well avoided if we had UT.

**Comment by carmal891** [comment]
picking up UT for ReconcileCOSInstance
