### ISSUE TITLE
Build and push controller image post-merge

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#332]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**

This PR is for building/pushing image via k8s build process, more info - https://github.com/kubernetes/test-infra/blob/c5f5b3155733140e6cbd83185862df85935c0f1c/config/jobs/image-pushing/README.md

**Tasks:**

- [x] Staging repo - https://github.com/kubernetes/k8s.io/pull/2640
- [x] Makefile changes for multi-arch - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/335
- [x] cloudbuild.yaml - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/336
- [x] Prow jobs - https://github.com/kubernetes/test-infra/pull/23494

**Comment by mkumatag** [comment]
All the required PRs got merged, will close the issue after the test run.

**Comment by mkumatag** [comment]
Now we have the image built and pushed via prow CI/CD,

```
$ manifest-tool inspect gcr.io/k8s-staging-capi-ibmcloud/cluster-api-ibmcloud-controller:v20210908-v0.0.1-116-g92635f58
Name:   gcr.io/k8s-staging-capi-ibmcloud/cluster-api-ibmcloud-controller:v20210908-v0.0.1-116-g92635f58 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:cec5bb65784656f127a53b3997c6c98972f6992f5ea3ed9ff50a62653f6abd73
 * Contains 2 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:93da2a2a101edfd15c41e56efb3e409b79e7a73213eb09a08af67fdd5bec66d7
1  Mfst Length: 739
1     Platform:
1           -      OS: linux
1           - OS Vers:
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant:
1           - Feature:
1     # Layers: 2
         layer 1: digest = sha256:b49b96595fd4bd6de7cb7253fe5e89d242d0eb4f993b2b8280c0581c3a62ddc2
         layer 2: digest = sha256:995cc74b4843963e34248c04757dc4749e8c286cad87c999f4a19e5dffd1f557

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:ee6822642116ed8894186d2336ba32a58e00f4fdbcb006d712b02507bcd61e15
2  Mfst Length: 739
2     Platform:
2           -      OS: linux
2           - OS Vers:
2           - OS Feat: []
2           -    Arch: ppc64le
2           - Variant:
2           - Feature:
2     # Layers: 2
         layer 1: digest = sha256:b49b96595fd4bd6de7cb7253fe5e89d242d0eb4f993b2b8280c0581c3a62ddc2
         layer 2: digest = sha256:b847f6b5abb10da11b432f15bae28bccc63b0d4eabe14bd5ddd1cd1973a7a851
```

Prow log: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-ibmcloud-push-images/1435482876136132608
